# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-26 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_auto_20190424_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycomments', to='wall_app.User'),
        ),
    ]
