# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-26 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0004_auto_20190426_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='wall_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_wall_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wall_post_Comment', to='wall_app.wall_post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_Comment', to='wall_app.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='wall_post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_post', to='wall_app.User'),
        ),
    ]
